[package]
name = "knightLaser2"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serialport = "4.7.2"
tokio = { version = "1.45.1" }
serde = "1.0.219"